name: OEA - Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10,12,15,18 * * *"  # 07:00, 09:00, 12:00, 15:00 America/Sao_Paulo

env:
  TZ: America/Sao_Paulo
  PYTHONUNBUFFERED: "1"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Create credentials file from secret
        run: printf '%s' "${{ secrets.GOOGLE_CREDENTIALS }}" > credenciais.json

      - name: Validate credentials JSON
        run: python -c "import json; json.load(open('credenciais.json','r',encoding='utf-8')); print('OK')"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Ensure logs dir
        run: mkdir -p logs

      - name: Sanity check (scripts)
        run: |
          [ -f atualizar_oea.py ] || { echo 'missing atualizar_oea.py'; exit 1; }
          [ -f obras_compilar_csv.py ] || echo 'warn: obras_compilar_csv.py ausente'
          [ -f replicar_bd_mensal.py ] || echo 'warn: replicar_bd_mensal.py ausente'
          [ -f replicar_esteira_oea.py ] || echo 'warn: replicar_esteira_oea.py ausente'

      - name: Run pipeline
        run: python -u -X utf8 atualizar_oea.py
