name: OEA - Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10,12,15,18 * * *"  # 07:00, 09:00, 12:00, 15:00 America/Sao_Paulo

env:
  TZ: America/Sao_Paulo
  PYTHONUNBUFFERED: "1"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # NÃO imprime o secret. Passa via env p/ o Python decodificar.
      - name: Decode credentials (from GOOGLE_CREDENTIALS_B64)
        env:
          CREDS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        run: |
          python - <<'PY'
import os, base64, json, sys
b64 = os.environ.get("CREDS_B64")
if not b64:
    print("Secret GOOGLE_CREDENTIALS_B64 ausente."); sys.exit(2)
data = base64.b64decode(b64)
open("credenciais.json","wb").write(data)
json.load(open("credenciais.json","r",encoding="utf-8"))
print("credenciais.json OK")
PY

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Ensure logs dir
        run: mkdir -p logs

      - name: Sanity check (scripts)
        run: |
          [ -f atualizar_oea.py ] || { echo 'missing atualizar_oea.py'; exit 1; }

      - name: Run pipeline
        run: python -u -X utf8 atualizar_oea.py
