name: OEA - Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10,12,15,18 * * *"  # 07:00, 09:00, 12:00, 15:00 America/Sao_Paulo

env:
  TZ: America/Sao_Paulo
  PYTHONUNBUFFERED: "1"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Write credenciais.json from GOOGLE_CREDENTIALS
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python -c "import os,sys,json,pathlib; v=os.environ.get('GOOGLE_CREDENTIALS'); \
            (print('Secret GOOGLE_CREDENTIALS ausente') or sys.exit(2)) if not v else None; \
            json.loads(v); pathlib.Path('credenciais.json').write_text(v, encoding='utf-8'); \
            print('credenciais.json OK')"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install google-api-python-client google-auth google-auth-httplib2 gspread gspread-formatting oauth2client pandas numpy
          fi

      - name: Ensure logs dir
        run: mkdir -p logs

      - name: Run pipeline
        run: python -u -X utf8 atualizar_oea.py
